version: '3'
services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5001:3000"
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - DB_PORT=3306
      - DB_USER=trucotrato
      - DB_PASSWORD=2121
      - DB_NAME=PlataformaTrucoTrato

  db:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: jdelgado
      MYSQL_DATABASE: PlataformaTrucoTrato
      MYSQL_USER: root
      MYSQL_PASSWORD: jdelgado
    ports:
      - "3306:3306"
    volumes:
      - ./Backend/src/db/databaseCreation.sql:/docker-entrypoint-initdb.d/databaseCreation.sql
      - db_data:/var/lib/mysql

volumes:
  db_data:
